# 通用配置（这些配置是没有必要放到apollo去的固定配置[或者增加可读性的配置]，如果容易变动的配置，最好放到apollo里进行配置）

server:
  context-path: /push
  port: 10580
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 2048
  undertow:
    io-threads: 8
    worker-threads: 248
    buffer-size: 1024


spring:
  ### 项目基本信息
  application:
    name: "${server_name}"
  profiles:
    #### 只有设置active属性，才会在开发环境加载dev的配置，default：dev不会加载下方配置
    active: ${project.environment}
  ### http配置
  http:
    encoding:
      charset: UTF-8
      force: true

  ### jackson配置
  jackson:
    serialization:
      write_dates_as_timestamps: false
      fail_on_empty_beans: false
    deserialization:
      fail_on_unknown_properties: false
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null

  mvc:
    throw-exception-if-no-handler-found: true
    #### 只允许通过static目录静态资源访问，这样不会有默认的RecourseHandler,而导致无法正常404抛出异常
    #### 使用之后，springboot默认的资源根路径，都需要添加/static前缀
    static-path-pattern: /static/**

  output:
    ansi:
      enabled: always

  ### 数据库基本配置
  datasource:
      type: com.zaxxer.hikari.HikariDataSource
      hikari:
        connection-init-sql: SET NAMES utf8mb4

logging:
  config: "classpath:config/log4j2-${spring.profiles.active}.xml"

## 监控
info:
  app:
    name: "${server_name}"
    encoding: UTF-8

# 部分监控指标配置已移到配置中心，方便后期统一管理


## spring cloud相关
ribbon:
  eureka:
   enabled: false

feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000 # 默认超时时间

## 自定义配置
htonline:
  wrapper.enabled: true
  httpclient.enabled: false
  okhttp.enabled: true
  executor.enabled: true
  cache-manage:
    enabled: true
    basePackage: com.huatu.tiku
    prefix:
      redis: "${spring.application.name}"


# 不同环境的不同配置，也可以放在apollo，除了开发使用的特殊debug等配置，一般不建议放在这里
---
spring:
  profiles: dev

server:
  error:
    include-stacktrace: always
debug: true

---
spring:
  profiles: test

server:
  error:
    include-stacktrace: always
---
spring:
  profiles: release

---
spring:
  profiles: product
